load "../common/common"

declare -gra OPTIONS=("--stdin")

@test "parser: comparison, with an one less sign" {
	declare -r INPUT="x < y"
	declare -r OUTPUT='{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"offset":0,"type":"sequence"},{"children":[{"children":[{"offset":0,"type":"base_identifier","value":"x"}],"type":"identifier"}],"type":"atom"}],"type":"sequence"}],"type":"unary"},{"offset":2,"type":"sequence"}],"type":"sequence"}],"type":"product"},{"offset":2,"type":"sequence"}],"type":"sequence"}],"type":"sum"},{"children":[{"children":[{"offset":2,"type":"less","value":"<"},{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"offset":4,"type":"sequence"},{"children":[{"children":[{"offset":4,"type":"base_identifier","value":"y"}],"type":"identifier"}],"type":"atom"}],"type":"sequence"}],"type":"unary"},{"offset":5,"type":"sequence"}],"type":"sequence"}],"type":"product"},{"offset":5,"type":"sequence"}],"type":"sequence"}],"type":"sum"}],"type":"sequence"},{"offset":5,"type":"sequence"}],"type":"sequence"}],"type":"sequence"}],"type":"comparison"},{"offset":5,"type":"sequence"}],"type":"sequence"}],"type":"equality"},{"offset":5,"type":"sequence"}],"type":"sequence"}],"type":"conjunction"},{"offset":5,"type":"sequence"}],"type":"sequence"}],"type":"disjunction"}'
	test_json_output
}

@test "parser: comparison, with an one less-or-equal sign" {
	declare -r INPUT="x <= y"
	declare -r OUTPUT='{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"offset":0,"type":"sequence"},{"children":[{"children":[{"offset":0,"type":"base_identifier","value":"x"}],"type":"identifier"}],"type":"atom"}],"type":"sequence"}],"type":"unary"},{"offset":2,"type":"sequence"}],"type":"sequence"}],"type":"product"},{"offset":2,"type":"sequence"}],"type":"sequence"}],"type":"sum"},{"children":[{"children":[{"offset":2,"type":"less_or_equal","value":"<="},{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"offset":5,"type":"sequence"},{"children":[{"children":[{"offset":5,"type":"base_identifier","value":"y"}],"type":"identifier"}],"type":"atom"}],"type":"sequence"}],"type":"unary"},{"offset":6,"type":"sequence"}],"type":"sequence"}],"type":"product"},{"offset":6,"type":"sequence"}],"type":"sequence"}],"type":"sum"}],"type":"sequence"},{"offset":6,"type":"sequence"}],"type":"sequence"}],"type":"sequence"}],"type":"comparison"},{"offset":6,"type":"sequence"}],"type":"sequence"}],"type":"equality"},{"offset":6,"type":"sequence"}],"type":"sequence"}],"type":"conjunction"},{"offset":6,"type":"sequence"}],"type":"sequence"}],"type":"disjunction"}'
	test_json_output
}

@test "parser: comparison, with an one great sign" {
	declare -r INPUT="x > y"
	declare -r OUTPUT='{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"offset":0,"type":"sequence"},{"children":[{"children":[{"offset":0,"type":"base_identifier","value":"x"}],"type":"identifier"}],"type":"atom"}],"type":"sequence"}],"type":"unary"},{"offset":2,"type":"sequence"}],"type":"sequence"}],"type":"product"},{"offset":2,"type":"sequence"}],"type":"sequence"}],"type":"sum"},{"children":[{"children":[{"offset":2,"type":"great","value":">"},{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"offset":4,"type":"sequence"},{"children":[{"children":[{"offset":4,"type":"base_identifier","value":"y"}],"type":"identifier"}],"type":"atom"}],"type":"sequence"}],"type":"unary"},{"offset":5,"type":"sequence"}],"type":"sequence"}],"type":"product"},{"offset":5,"type":"sequence"}],"type":"sequence"}],"type":"sum"}],"type":"sequence"},{"offset":5,"type":"sequence"}],"type":"sequence"}],"type":"sequence"}],"type":"comparison"},{"offset":5,"type":"sequence"}],"type":"sequence"}],"type":"equality"},{"offset":5,"type":"sequence"}],"type":"sequence"}],"type":"conjunction"},{"offset":5,"type":"sequence"}],"type":"sequence"}],"type":"disjunction"}'
	test_json_output
}

@test "parser: comparison, with an one great-or-equal sign" {
	declare -r INPUT="x >= y"
	declare -r OUTPUT='{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"offset":0,"type":"sequence"},{"children":[{"children":[{"offset":0,"type":"base_identifier","value":"x"}],"type":"identifier"}],"type":"atom"}],"type":"sequence"}],"type":"unary"},{"offset":2,"type":"sequence"}],"type":"sequence"}],"type":"product"},{"offset":2,"type":"sequence"}],"type":"sequence"}],"type":"sum"},{"children":[{"children":[{"offset":2,"type":"great_or_equal","value":">="},{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"offset":5,"type":"sequence"},{"children":[{"children":[{"offset":5,"type":"base_identifier","value":"y"}],"type":"identifier"}],"type":"atom"}],"type":"sequence"}],"type":"unary"},{"offset":6,"type":"sequence"}],"type":"sequence"}],"type":"product"},{"offset":6,"type":"sequence"}],"type":"sequence"}],"type":"sum"}],"type":"sequence"},{"offset":6,"type":"sequence"}],"type":"sequence"}],"type":"sequence"}],"type":"comparison"},{"offset":6,"type":"sequence"}],"type":"sequence"}],"type":"equality"},{"offset":6,"type":"sequence"}],"type":"sequence"}],"type":"conjunction"},{"offset":6,"type":"sequence"}],"type":"sequence"}],"type":"disjunction"}'
	test_json_output
}

@test "parser: comparison, with some less signs" {
	declare -r INPUT="x < y < z"
	declare -r OUTPUT='{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"offset":0,"type":"sequence"},{"children":[{"children":[{"offset":0,"type":"base_identifier","value":"x"}],"type":"identifier"}],"type":"atom"}],"type":"sequence"}],"type":"unary"},{"offset":2,"type":"sequence"}],"type":"sequence"}],"type":"product"},{"offset":2,"type":"sequence"}],"type":"sequence"}],"type":"sum"},{"children":[{"children":[{"offset":2,"type":"less","value":"<"},{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"offset":4,"type":"sequence"},{"children":[{"children":[{"offset":4,"type":"base_identifier","value":"y"}],"type":"identifier"}],"type":"atom"}],"type":"sequence"}],"type":"unary"},{"offset":6,"type":"sequence"}],"type":"sequence"}],"type":"product"},{"offset":6,"type":"sequence"}],"type":"sequence"}],"type":"sum"}],"type":"sequence"},{"children":[{"children":[{"offset":6,"type":"less","value":"<"},{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"offset":8,"type":"sequence"},{"children":[{"children":[{"offset":8,"type":"base_identifier","value":"z"}],"type":"identifier"}],"type":"atom"}],"type":"sequence"}],"type":"unary"},{"offset":9,"type":"sequence"}],"type":"sequence"}],"type":"product"},{"offset":9,"type":"sequence"}],"type":"sequence"}],"type":"sum"}],"type":"sequence"},{"offset":9,"type":"sequence"}],"type":"sequence"}],"type":"sequence"}],"type":"sequence"}],"type":"comparison"},{"offset":9,"type":"sequence"}],"type":"sequence"}],"type":"equality"},{"offset":9,"type":"sequence"}],"type":"sequence"}],"type":"conjunction"},{"offset":9,"type":"sequence"}],"type":"sequence"}],"type":"disjunction"}'
	test_json_output
}

@test "parser: comparison, with one less, less-or-equal, great and great-or-equal signs" {
	declare -r INPUT="x < y <= z > w >= t"
	declare -r OUTPUT='{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"offset":0,"type":"sequence"},{"children":[{"children":[{"offset":0,"type":"base_identifier","value":"x"}],"type":"identifier"}],"type":"atom"}],"type":"sequence"}],"type":"unary"},{"offset":2,"type":"sequence"}],"type":"sequence"}],"type":"product"},{"offset":2,"type":"sequence"}],"type":"sequence"}],"type":"sum"},{"children":[{"children":[{"offset":2,"type":"less","value":"<"},{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"offset":4,"type":"sequence"},{"children":[{"children":[{"offset":4,"type":"base_identifier","value":"y"}],"type":"identifier"}],"type":"atom"}],"type":"sequence"}],"type":"unary"},{"offset":6,"type":"sequence"}],"type":"sequence"}],"type":"product"},{"offset":6,"type":"sequence"}],"type":"sequence"}],"type":"sum"}],"type":"sequence"},{"children":[{"children":[{"offset":6,"type":"less_or_equal","value":"<="},{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"offset":9,"type":"sequence"},{"children":[{"children":[{"offset":9,"type":"base_identifier","value":"z"}],"type":"identifier"}],"type":"atom"}],"type":"sequence"}],"type":"unary"},{"offset":11,"type":"sequence"}],"type":"sequence"}],"type":"product"},{"offset":11,"type":"sequence"}],"type":"sequence"}],"type":"sum"}],"type":"sequence"},{"children":[{"children":[{"offset":11,"type":"great","value":">"},{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"offset":13,"type":"sequence"},{"children":[{"children":[{"offset":13,"type":"base_identifier","value":"w"}],"type":"identifier"}],"type":"atom"}],"type":"sequence"}],"type":"unary"},{"offset":15,"type":"sequence"}],"type":"sequence"}],"type":"product"},{"offset":15,"type":"sequence"}],"type":"sequence"}],"type":"sum"}],"type":"sequence"},{"children":[{"children":[{"offset":15,"type":"great_or_equal","value":">="},{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"offset":18,"type":"sequence"},{"children":[{"children":[{"offset":18,"type":"base_identifier","value":"t"}],"type":"identifier"}],"type":"atom"}],"type":"sequence"}],"type":"unary"},{"offset":19,"type":"sequence"}],"type":"sequence"}],"type":"product"},{"offset":19,"type":"sequence"}],"type":"sequence"}],"type":"sum"}],"type":"sequence"},{"offset":19,"type":"sequence"}],"type":"sequence"}],"type":"sequence"}],"type":"sequence"}],"type":"sequence"}],"type":"sequence"}],"type":"comparison"},{"offset":19,"type":"sequence"}],"type":"sequence"}],"type":"equality"},{"offset":19,"type":"sequence"}],"type":"sequence"}],"type":"conjunction"},{"offset":19,"type":"sequence"}],"type":"sequence"}],"type":"disjunction"}'
	test_json_output
}
