load "../common/common"

declare -gra OPTIONS=("--stdin")

@test "parser: expression, with a minus and a multiplication" {
	declare -r INPUT="-x * y"
	declare -r OUTPUT='{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"offset":0,"type":"minus","value":"-"},{"offset":1,"type":"sequence"}],"type":"sequence"},{"children":[{"children":[{"offset":1,"type":"base_identifier","value":"x"}],"type":"identifier"}],"type":"atom"}],"type":"sequence"}],"type":"unary"},{"children":[{"children":[{"offset":3,"type":"star","value":"*"},{"children":[{"children":[{"offset":5,"type":"sequence"},{"children":[{"children":[{"offset":5,"type":"base_identifier","value":"y"}],"type":"identifier"}],"type":"atom"}],"type":"sequence"}],"type":"unary"}],"type":"sequence"},{"offset":6,"type":"sequence"}],"type":"sequence"}],"type":"sequence"}],"type":"product"},{"offset":6,"type":"sequence"}],"type":"sequence"}],"type":"sum"},{"offset":6,"type":"sequence"}],"type":"sequence"}],"type":"comparison"},{"offset":6,"type":"sequence"}],"type":"sequence"}],"type":"equality"},{"offset":6,"type":"sequence"}],"type":"sequence"}],"type":"conjunction"},{"offset":6,"type":"sequence"}],"type":"sequence"}],"type":"disjunction"}'
	test_json_output
}

@test "parser: expression, with a minus, a multiplication and a grouping" {
	declare -r INPUT="-(x * y)"
	declare -r OUTPUT='{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"offset":0,"type":"minus","value":"-"},{"offset":1,"type":"sequence"}],"type":"sequence"},{"children":[{"children":[{"children":[{"offset":1,"type":"nothing"},{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"offset":2,"type":"sequence"},{"children":[{"children":[{"offset":2,"type":"base_identifier","value":"x"}],"type":"identifier"}],"type":"atom"}],"type":"sequence"}],"type":"unary"},{"children":[{"children":[{"offset":4,"type":"star","value":"*"},{"children":[{"children":[{"offset":6,"type":"sequence"},{"children":[{"children":[{"offset":6,"type":"base_identifier","value":"y"}],"type":"identifier"}],"type":"atom"}],"type":"sequence"}],"type":"unary"}],"type":"sequence"},{"offset":7,"type":"sequence"}],"type":"sequence"}],"type":"sequence"}],"type":"product"},{"offset":7,"type":"sequence"}],"type":"sequence"}],"type":"sum"},{"offset":7,"type":"sequence"}],"type":"sequence"}],"type":"comparison"},{"offset":7,"type":"sequence"}],"type":"sequence"}],"type":"equality"},{"offset":7,"type":"sequence"}],"type":"sequence"}],"type":"conjunction"},{"offset":7,"type":"sequence"}],"type":"sequence"}],"type":"disjunction"}],"type":"sequence"},{"offset":7,"type":"nothing"}],"type":"sequence"}],"type":"atom"}],"type":"sequence"}],"type":"unary"},{"offset":8,"type":"sequence"}],"type":"sequence"}],"type":"product"},{"offset":8,"type":"sequence"}],"type":"sequence"}],"type":"sum"},{"offset":8,"type":"sequence"}],"type":"sequence"}],"type":"comparison"},{"offset":8,"type":"sequence"}],"type":"sequence"}],"type":"equality"},{"offset":8,"type":"sequence"}],"type":"sequence"}],"type":"conjunction"},{"offset":8,"type":"sequence"}],"type":"sequence"}],"type":"disjunction"}'
	test_json_output
}

@test "parser: expression, with a multiplication and an addition" {
	declare -r INPUT="x * y + z"
	declare -r OUTPUT='{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"offset":0,"type":"sequence"},{"children":[{"children":[{"offset":0,"type":"base_identifier","value":"x"}],"type":"identifier"}],"type":"atom"}],"type":"sequence"}],"type":"unary"},{"children":[{"children":[{"offset":2,"type":"star","value":"*"},{"children":[{"children":[{"offset":4,"type":"sequence"},{"children":[{"children":[{"offset":4,"type":"base_identifier","value":"y"}],"type":"identifier"}],"type":"atom"}],"type":"sequence"}],"type":"unary"}],"type":"sequence"},{"offset":6,"type":"sequence"}],"type":"sequence"}],"type":"sequence"}],"type":"product"},{"children":[{"children":[{"offset":6,"type":"plus","value":"+"},{"children":[{"children":[{"children":[{"children":[{"offset":8,"type":"sequence"},{"children":[{"children":[{"offset":8,"type":"base_identifier","value":"z"}],"type":"identifier"}],"type":"atom"}],"type":"sequence"}],"type":"unary"},{"offset":9,"type":"sequence"}],"type":"sequence"}],"type":"product"}],"type":"sequence"},{"offset":9,"type":"sequence"}],"type":"sequence"}],"type":"sequence"}],"type":"sum"},{"offset":9,"type":"sequence"}],"type":"sequence"}],"type":"comparison"},{"offset":9,"type":"sequence"}],"type":"sequence"}],"type":"equality"},{"offset":9,"type":"sequence"}],"type":"sequence"}],"type":"conjunction"},{"offset":9,"type":"sequence"}],"type":"sequence"}],"type":"disjunction"}'
	test_json_output
}

@test "parser: expression, with a multiplication, an addition and a grouping" {
	declare -r INPUT="x * (y + z)"
	declare -r OUTPUT='{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"offset":0,"type":"sequence"},{"children":[{"children":[{"offset":0,"type":"base_identifier","value":"x"}],"type":"identifier"}],"type":"atom"}],"type":"sequence"}],"type":"unary"},{"children":[{"children":[{"offset":2,"type":"star","value":"*"},{"children":[{"children":[{"offset":4,"type":"sequence"},{"children":[{"children":[{"children":[{"offset":4,"type":"nothing"},{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"children":[{"offset":5,"type":"sequence"},{"children":[{"children":[{"offset":5,"type":"base_identifier","value":"y"}],"type":"identifier"}],"type":"atom"}],"type":"sequence"}],"type":"unary"},{"offset":7,"type":"sequence"}],"type":"sequence"}],"type":"product"},{"children":[{"children":[{"offset":7,"type":"plus","value":"+"},{"children":[{"children":[{"children":[{"children":[{"offset":9,"type":"sequence"},{"children":[{"children":[{"offset":9,"type":"base_identifier","value":"z"}],"type":"identifier"}],"type":"atom"}],"type":"sequence"}],"type":"unary"},{"offset":10,"type":"sequence"}],"type":"sequence"}],"type":"product"}],"type":"sequence"},{"offset":10,"type":"sequence"}],"type":"sequence"}],"type":"sequence"}],"type":"sum"},{"offset":10,"type":"sequence"}],"type":"sequence"}],"type":"comparison"},{"offset":10,"type":"sequence"}],"type":"sequence"}],"type":"equality"},{"offset":10,"type":"sequence"}],"type":"sequence"}],"type":"conjunction"},{"offset":10,"type":"sequence"}],"type":"sequence"}],"type":"disjunction"}],"type":"sequence"},{"offset":10,"type":"nothing"}],"type":"sequence"}],"type":"atom"}],"type":"sequence"}],"type":"unary"}],"type":"sequence"},{"offset":11,"type":"sequence"}],"type":"sequence"}],"type":"sequence"}],"type":"product"},{"offset":11,"type":"sequence"}],"type":"sequence"}],"type":"sum"},{"offset":11,"type":"sequence"}],"type":"sequence"}],"type":"comparison"},{"offset":11,"type":"sequence"}],"type":"sequence"}],"type":"equality"},{"offset":11,"type":"sequence"}],"type":"sequence"}],"type":"conjunction"},{"offset":11,"type":"sequence"}],"type":"sequence"}],"type":"disjunction"}'
	test_json_output
}
