@startuml
!include sequential_parser.plantuml
!include not_sequential_parser.plantuml

abstract class binary_parser {
	+ <i>final</i> parse()
	# <i>virtual</i> is_sequential()
	# <i>virtual</i> process_left_result()
	# <i>virtual</i> process_right_result()
	# <i>virtual</i> combine_results()
}

binary_parser <|-- sequential_parser
binary_parser <|-- not_sequential_parser
@enduml
